groups:
  - name: solo_backend.rules
    rules:
      - alert: HighP95Latency
        expr: |
          histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le)) > 3
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "High 95th percentile latency (>3s) detected"
          description: |
            The 95th percentile latency across all endpoints has exceeded 3 seconds for the last 2 minutes.
            Investigate the backend service. 