services:
  backend:
    image: solorag-backend-cpu
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      args:
        BUILD_MODE: cpu
        BASE_IMAGE: python:3.11-slim
    ports:
      - "8000:8000"
    volumes:
      - ../artifacts:/app/artifacts:ro
    depends_on:
      - ollama
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://localhost:11434
      # By default, the entrypoint uses llama3:8b-instruct-q5_K_M.
      # Uncomment the line below to use a different model.
      # The entrypoint script will automatically pull this model on startup.
      # - OLLAMA_MODEL=mistral:7b-instruct-q5_K_M

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend

  streamlit:
    image: solorag-backend-cpu
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      args:
        BUILD_MODE: cpu
        BASE_IMAGE: python:3.11-slim
    command: >
      bash -c "streamlit run /app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  ollama_data: {}
