# .github/workflows/ci.yml (snippet)
- uses: actions/setup-python@v5
  with: {python-version: '3.11'}
- run: pip install -r requirements.txt -r requirements-dev.txt
- run: ruff check .
- run: mypy app
- run: pytest -q